### ISSUE TITLE
Movable Features 位移信标

### ISSUE THREAD

**Issue by AndyMartin123** [ttdly/ONI-Mods#23]
uplicant goes to conduct a survey of the building and the beacon does not appear upon completion, and those beacons that were before the update just disappeared when activated. Tried to disabled the mod load save make a new save then enable the mod and load again nothing changed. There may be a conflict of mods, but everything worked before the update.

[handyprint](https://steamcommunity.com/profiles/76561198169576233) 14 minutes ago 
After surveying no beacon appears

[Unholyrage](https://steamcommunity.com/id/DarkEviLx17) 23 minutes ago 
Why then are there 4 skills left in the construction branch? I have a dup in my colony with the “Masterworks” skill and still nothing works. I'm probably missing something.

[handyprint](https://steamcommunity.com/profiles/76561198169576233) 34 minutes ago 
Unholyrage.... It now requires the "Masterworks" skill

**Comment by ttdly** [comment]
# Mod description

The mod has added a building called "Displacement Beacon" which allows you to build and move already surveyed items. When moving the item, it will be covered with Neutronium.

**Comment by ttdly** [comment]
Anyway, thank you for your feedback here.

**Comment by ttdly** [comment]
> 哥哥，steam上面的版本要不要先回退一下？？？？ 周末想玩缺氧！！！！！ release版本找不到1.12版本，只有最新版本

https://github.com/ttdly/ONI-Mods/releases/tag/v1.1.3-pack
这是上个版本
