### ISSUE TITLE
移位信标

### ISSUE THREAD

**Issue by ugrg** [ttdly/ONI-Mods#30]
我发现我用移位信标移动的反熵中和器不见了。一共消失了两个。

**Comment by ttdly** [comment]
> 我发现我用移位信标移动的反熵中和器不见了。一共消失了两个。

你好，我之前在评论区看到这一个问题之后就尝试复现这个情况，但是并没有复现出来，所以我没法确定问题出在哪里，也不知道怎么修复，你在使用 debug 的移动功能会出现这样的情况吗？

**Comment by ugrg** [comment]
像是在存档再读档后消失的，我记得移动的时候看到他出现了，后来准备再移动个地方的时候就找不到了。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月28日 20:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ttdly/ONI-Mods] 移位信标 (Issue #30) |

我发现我用移位信标移动的反熵中和器不见了。一共消失了两个。

你好，我之前在评论区看到这一个问题之后就尝试复现这个情况，但是并没有复现出来，所以我没法确定问题出在哪里，也不知道怎么修复，你在使用 debug 的移动功能会出现这样的情况吗？

**Comment by ttdly** [comment]
> 像是在存档再读档后消失的，我记得移动的时候看到他出现了，后来准备再移动个地方的时候就找不到了。

存档方便发一下吗？我这段时间忙完看看，发送到我 GitHub 绑定的邮箱里也行

**Comment by ugrg** [comment]
记的特别清楚的是在这里我放了一个，后来就没了。













--

ugrg




在 2023-12-28 21:39:14，"秃头灯笼鱼" ***@***.***> 写道：

像是在存档再读档后消失的，我记得移动的时候看到他出现了，后来准备再移动个地方的时候就找不到了。

存档方便发一下吗？我这段时间忙完看看，发送到我 GitHub 绑定的邮箱里也行

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

从网易163邮箱发来的超大附件推荐客户端极速下载
放射性的深渊 Cycle 3141.sav (31.93M, 2024年1月13日 9:22 到期)
下载

**Comment by ttdly** [comment]
> 记的特别清楚的是在这里我放了一个，后来就没了。
下载不了，邮箱里也不行，直接发到 ttdlyu@163.com，我先确认一下存档里是有反熵中和器的吧？
