### ISSUE TITLE
国际化问题

### ISSUE THREAD

**Issue by neavo** [ttdly/ONI-Mods#33]
想请教一个跟这些MOD没有太大关系的问题，如果大佬觉得不合适可以直接关闭。

我想给自己的MOD添加国际化支持，参考大佬的代码，编纂了 zh.po 翻译文件，在 OnLoad 方法中进行了注册

> new PLocalization().Register();
LocString.CreateLocStringKeys(typeof(ModStrings), "");

然后在 Options 类中进行了标注

>
      [RestartRequired]
      [JsonObject(MemberSerialization.OptIn)]
      public class Config
      {
          [Option("ModStrings.Config.MULTIPLIER_TITLE", "ModStrings.Config.MULTIPLIER_TOOLTIPS", null)]
          [Limit(1, 20)]
          [JsonProperty]
          public int Multiplier
          {
              get;
              set;
          }
  
          public Config()
          {
              Multiplier = 5;
          }
      }

游戏内的内容比如建筑菜单等地方可以正常的读取po文件中的数据了，但是游戏模组设置界面的菜单中的文本却读不到，永远是默认值，能否请大佬指点一下问题所在

**Comment by neavo** [comment]
[project.zip](https://github.com/ttdly/ONI-Mods/files/15145282/project.zip)

附上相关文件

**Comment by ttdly** [comment]
我也很困扰，因为我最近也是遇到这个问题，我也不知道怎么搞。我有空再看看，如果解决了我会告诉你。

**Comment by neavo** [comment]
（手动捂脸
加油

**Comment by neavo** [comment]
我看了一下其他的MOD，有的MOD采用的方法是在 PLocalization 前手动load对应的国际化文件把文本填给 LocString 的变量以后再初始化 。。。
应该不需要这么蠢的方式吧 。。。

**Comment by ttdly** [comment]
> 我看了一下其他的MOD，有的MOD采用的方法是在 PLocalization 前手动load对应的国际化文件把文本填给 LocString 的变量以后再初始化 。。。 应该不需要这么蠢的方式吧 。。。

有可能，只要能解决就行，我最近没空看。或者你可以看看 SGT 是怎么实现国际化的。
