### ISSUE TITLE
Debris Thermostat - Every other item is not cooled.

### ISSUE THREAD

**Issue by Caseyckk** [ttdly/ONI-Mods#34]
I am passing ~250*C igneous rock through this and every 2nd item is not cooled.
[22*C, 250*C, 22*C, 250*C, 22*C, 250*C, 22*C, 250*C, 22*C]

**Comment by ttdly** [comment]
Ok, I will check it later.



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/27/2024 13:41 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [ttdly/ONI-Mods] Debris Thermostat - Every other item is not cooled. (Issue #34) |

I am passing ~250C igneous rock through this and every 2nd item is not cooled.
[22C, 250C, 22C, 250C, 22C, 250C, 22C, 250C, 22C]

**Comment by ttdly** [comment]
Sorry, I cannot reproduce this problem.

**Comment by Caseyckk** [comment]
It persists through a full restart of the game. 
Using the DLC. 
The filter is made of steel and placed into 50kg of steam for steam turbines.
Set to 22C.

**Comment by ttdly** [comment]
Ok, thanks for the addtional infomation.



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/27/2024 22:12 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ttdly/ONI-Mods] Debris Thermostat - Every other item is not cooled. (Issue #34) |

It persists through a full restart of the game.
Using the DLC.
The filter is made of steel and placed into 50kg of steam for steam turbines.
Set to 22C.

**Comment by Caseyckk** [comment]
This appears to have resolved the issue. Thank you for your work!
